#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication decomposePar -allRegions -decomposeParDict system/decomposeParDict

runParallel $(getApplication)

runApplication reconstructPar -allRegions

#------------------------------------------------------------------------------
